backend = "glx";
vsync = true;
use-damage = true;
detect-client-leader = true;

fading = true;
fade-in-step = 0.06;
fade-out-step = 0.06;
fade-delta = 8;

blur-method = "dual_kawase";
blur-strength = 4;

rules = (
  {
    match = "window_type = 'normal'";
    animations = (
      {
        triggers = ["open"];
        preset = "appear";
        duration = 0.22;
      },
      {
        triggers = ["close"];
        preset = "disappear";
        duration = 0.20;
      },
      {
        triggers = ["focus"];
        preset = "appear";
        duration = 0.28;
      },
      {
	triggers = ["show"];
	preset = "appear";
	duration = 0.28;
      },
      {
      	triggers = ["hide"];
	preset = "disappear";
	duration = 0.28;
      }
    );
  },

  {
    match = "window_type = 'normal' || window_type = 'dialog' || window_type = 'utility' || window_type = 'dock' || window_type = 'desktop'";
    corner-radius = 0;
  },

  {
    match = "window_type = 'normal' || window_type = 'dialog' || window_type = 'utility'";
    shadow = true;
    shadow-radius = 12;
    shadow-opacity = 0.50;
    shadow-offset-x = -10;
    shadow-offset-y = -10;
  },
  {
    match = "window_type = 'dock' || window_type = 'desktop' || class_g = 'Polybar' || class_g = 'bar-lessthan' || class_g = 'dwm'";
    shadow = false;
  },

  {
    match = "window_type = 'tooltip'";
    fade = true;
    shadow = true;
    opacity = 0.85;
    full-shadow = false;
  },
  {
    match = "window_type = 'popup_menu' || window_type = 'dropdown_menu'";
    opacity = 0.95;
  }
);
